name: Verify Credo

on: pull_request

jobs: 
  credo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.13.3]
        otp: [24]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v1
        id: mix-cache-credo
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }} 
      - name: Install Mix Dependencies
        if: steps.mix-cache-credo.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: ===> Credo
        run: mix credo --strict